spring.application.name=oauth2_GITHUB
server.port=8082
spring.security.oauth2.client.registration.github.client-id=Ov23liEEN7o2rDIiYwaN
spring.security.oauth2.client.registration.github.client-secret=43c614573be664b9baaf0a3713ad41cb422a7b9c